name: Go E2E BDD tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      - name: 'Create env file'
        shell: bash
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          TEST: ${{ secrets.TEST }}
        run: |
          touch .env
          echo $SMTP_SERVER
          echo "SMTP_SERVER=$SMTP_SERVER\n" >> .env
          echo "TEST=$TEST" >> .env
          cat .env

      - name: Run E2E tests
        run: make run-e2e

      - name: Remove env
        run: make docker-rm