name: Go

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      - name: Run unit tests
        run: export ALLURE_OUTPUT_PATH="$(pwd)" && go test ./... --race && echo "$(pwd)" && ls "$(pwd)"

    # - name: Load test report history
    #   uses: actions/checkout@v3
    #   if: always()
    #   continue-on-error: true
    #   with:
    #     ref: gh-pages
    #     path: gh-pages

    # - name: Build test report
    #   uses: simple-elf/allure-report-action@v1.7
    #   if: always()
    #   with:
    #     gh_pages: gh-pages
    #     allure_history: allure-history
    #     allure_results: build/allure-results

    # - name: Publish test report
    #   uses: peaceiris/actions-gh-pages@v3
    #   if: always()
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_branch: gh-pages
    #     publish_dir: allure-history
